[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
priority=10
autorestart=unexpected
startsecs=0
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:dovecot]
command=/usr/sbin/dovecot -F
priority=20
autorestart=unexpected
startsecs=0
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
