services:
  attacker:
    build:
      target: episode-02
  perimeter:
    environment:
      LAB_EPISODE: "02"
  operations:
    environment:
      LAB_EPISODE: "02"
  vault:
    environment:
      LAB_EPISODE: "02"
