services:
  attacker:
    build:
      target: episode-06
  perimeter:
    environment:
      LAB_EPISODE: "06"
  operations:
    environment:
      LAB_EPISODE: "06"
  vault:
    environment:
      LAB_EPISODE: "06"
