[global]
   workgroup = WORKGROUP
   server role = standalone server
   security = user
   interfaces = 172.30.30.20
   bind interfaces only = yes
   map to guest = Never
   restrict anonymous = 2
   server min protocol = SMB2

[research]
   path = /srv/research
   valid users = nightglass
   guest ok = no
   read only = yes
   browseable = yes
